In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import matplotlib 
from matplotlib import font_manager, rc 
from pandas import Series, DataFrame
import datetime
import matplotlib 
from matplotlib import font_manager, rc 
font_name = font_manager.FontProperties(fname = "C:/Windows/Fonts/malgun.ttf").get_name( ) 
rc('font', family = font_name) 
matplotlib.rcParams['axes.unicode_minus'] = False

In [97]:
da060118= pd.read_csv('D:/CSV/2022/DAY/220128.csv',sep = ",",encoding='CP949')

In [98]:
da060118.drop(da060118[da060118['ID']=='ID'].index, inplace=True)

In [99]:
da060118=da060118.reset_index(drop=True)

In [104]:
da060118.drop(da060118[da060118['HeartRate']==0.0].index, inplace=True)

In [108]:
da060118

,Time,GatewayID,ID,HeartRate,StepCount,Calorie,Km,DeviceWear,Rssi
0,2022-01-28T09:59:59.828,4C:11:AE:B9:5D:54,ce:75:da:5a:5e:82,95.0,2545.0,84.0,173.0,0.0,-78.0]
51,2022-01-28T09:59:59.278,4C:11:AE:B9:5D:2C,da:a9:21:02:6a:d1,106.0,231.0,7.0,14.0,0.0,-76.0]
53,2022-01-28T09:59:56.878,4C:11:AE:B9:5D:2C,f0:ec:c5:2e:59:9f,116.0,211.0,7.0,14.0,0.0,-85.0]
54,2022-01-28T09:59:59.328,4C:11:AE:B9:5D:2C,fe:2d:9c:89:36:99,80.0,60.0,1.0,3.0,0.0,-84.0]
57,2022-01-28T09:59:58.878,4C:11:AE:B9:5D:2C,e6:95:0b:5d:b6:d4,103.0,1368.0,38.0,88.0,0.0,-84.0]
...,...,...,...,...,...,...,...,...,...
1114101,2022-01-28T16:18:26.388,24:0A:C4:4E:E4:2C,da:a9:21:02:6a:d1,0.0,4317.0,139.0,290.0,1.0,-75.0]
1114102,2022-01-28T16:18:27.048,24:0A:C4:4E:E4:2C,f4:34:f0:d3:cc:dd,0.0,132.0,0.0,7.0,1.0,-78.0]
1114103,2022-01-28T16:18:25.668,24:0A:C4:4E:E4:2C,f0:ec:c5:2e:59:9f,0.0,3012.0,99.0,202.0,1.0,-77.0]
1114104,2022-01-28T16:18:26.848,24:0A:C4:4E:E4:2C,fe:2d:9c:89:36:99,0.0,2652.0,90.0,181.0,1.0,-71.0]
1114105,2022-01-28T16:18:26.888,24:0A:C4:4E:E4:2C,e7:ff:ea:af:b2:f6,0.0,751.0,27.0,47.0,1.0,-82.0]

In [71]:
da060118.drop(da060118[(da060118['HeartRate']==84.0)&(da060118['StepCount']==0.0)].index, inplace=True)

In [74]:
da060118

,Time,GatewayID,ID,HeartRate,StepCount,Calorie,Km,DeviceWear,Rssi
127053,2022-01-26T09:53:58.108,24:6F:28:D6:F3:5C,d4:c0:fc:21:e3:f0,78.0,388.0,9.0,24.0,0.0,-91.0]
127097,2022-01-26T09:53:58.994,24:0A:C4:4E:E4:2C,d4:c0:fc:21:e3:f0,78.0,388.0,9.0,24.0,0.0,-67.0]
127125,2022-01-26T09:53:59.343,24:0A:C4:4F:25:A8,d4:c0:fc:21:e3:f0,78.0,388.0,9.0,24.0,0.0,-85.0]
127159,2022-01-26T09:53:59.376,C4:4F:33:25:E7:7D,d4:c0:fc:21:e3:f0,78.0,388.0,9.0,24.0,0.0,-82.0]
127199,2022-01-26T09:54:00.400,4C:11:AE:B9:5D:2C,d4:c0:fc:21:e3:f0,78.0,388.0,9.0,24.0,0.0,-84.0]
...,...,...,...,...,...,...,...,...,...
1201164,2022-01-26T16:28:56.483,24:0A:C4:4E:CE:08,e7:71:ff:73:5a:fc,97.0,5278.0,179.0,364.0,0.0,-75.0]
1201190,2022-01-26T16:28:58.186,24:0A:C4:4E:3C:34,e7:71:ff:73:5a:fc,97.0,5278.0,179.0,364.0,0.0,-83.0]
1201198,2022-01-26T16:28:58.089,24:0A:C4:4E:E4:54,e7:71:ff:73:5a:fc,97.0,5278.0,179.0,364.0,0.0,-85.0]
1201230,2022-01-26T16:28:57.670,24:0A:C4:4E:A9:10,e7:71:ff:73:5a:fc,97.0,5278.0,179.0,364.0,0.0,-64.0]
1201262,2022-01-26T02:03:24.995,24:0A:C4:4E:A4:C4,e7:71:ff:73:5a:fc,97.0,5278.0,179.0,364.0,0.0,-64.0]

In [109]:
da060118=da060118.drop_duplicates(['HeartRate','StepCount','ID','Km','Calorie'], keep='last')
da060118=da060118.reset_index(drop=True)

In [110]:
da060118

,Time,GatewayID,ID,HeartRate,StepCount,Calorie,Km,DeviceWear,Rssi
0,2022-01-28T10:00:05.558,24:0A:C4:4E:CE:E0,fe:2d:9c:89:36:99,80.0,60.0,1.0,3.0,0.0,-85.0]
1,2022-01-28T10:00:09.010,24:0A:C4:4E:E4:2C,ce:75:da:5a:5e:82,95.0,2545.0,84.0,173.0,0.0,-89.0]
2,2022-01-28T10:00:12.839,24:0A:C4:4F:25:A8,da:a9:21:02:6a:d1,106.0,231.0,7.0,14.0,0.0,-85.0]
3,2022-01-28T10:00:14.081,24:0A:C4:4F:25:7C,e6:95:0b:5d:b6:d4,103.0,1368.0,38.0,88.0,0.0,-92.0]
4,2022-01-28T10:00:32.418,24:0A:C4:4E:CE:E0,f0:ec:c5:2e:59:9f,116.0,211.0,7.0,14.0,0.0,-86.0]
...,...,...,...,...,...,...,...,...,...
1299,2022-01-28T16:18:26.388,24:0A:C4:4E:E4:2C,da:a9:21:02:6a:d1,0.0,4317.0,139.0,290.0,1.0,-75.0]
1300,2022-01-28T16:18:27.048,24:0A:C4:4E:E4:2C,f4:34:f0:d3:cc:dd,0.0,132.0,0.0,7.0,1.0,-78.0]
1301,2022-01-28T16:18:25.668,24:0A:C4:4E:E4:2C,f0:ec:c5:2e:59:9f,0.0,3012.0,99.0,202.0,1.0,-77.0]
1302,2022-01-28T16:18:26.848,24:0A:C4:4E:E4:2C,fe:2d:9c:89:36:99,0.0,2652.0,90.0,181.0,1.0,-71.0]
1303,2022-01-28T16:18:26.888,24:0A:C4:4E:E4:2C,e7:ff:ea:af:b2:f6,0.0,751.0,27.0,47.0,1.0,-82.0]

In [111]:
da060118['Date']=da060118['Time']
for i in range(0,da060118['Time'].count()):
    da060118['Date'][i]=da060118['Time'][i][:10]+" "+da060118['Time'][i][11:16]

In [112]:
da060118=da060118.drop_duplicates(['ID','HeartRate','StepCount','Date'], keep='last')
da060118=da060118.reset_index(drop=True)

In [113]:
da060118

,Time,GatewayID,ID,HeartRate,StepCount,Calorie,Km,DeviceWear,Rssi,Date
0,2022-01-28T10:00:05.558,24:0A:C4:4E:CE:E0,fe:2d:9c:89:36:99,80.0,60.0,1.0,3.0,0.0,-85.0],2022-01-28 10:00
1,2022-01-28T10:00:09.010,24:0A:C4:4E:E4:2C,ce:75:da:5a:5e:82,95.0,2545.0,84.0,173.0,0.0,-89.0],2022-01-28 10:00
2,2022-01-28T10:00:12.839,24:0A:C4:4F:25:A8,da:a9:21:02:6a:d1,106.0,231.0,7.0,14.0,0.0,-85.0],2022-01-28 10:00
3,2022-01-28T10:00:14.081,24:0A:C4:4F:25:7C,e6:95:0b:5d:b6:d4,103.0,1368.0,38.0,88.0,0.0,-92.0],2022-01-28 10:00
4,2022-01-28T10:00:32.418,24:0A:C4:4E:CE:E0,f0:ec:c5:2e:59:9f,116.0,211.0,7.0,14.0,0.0,-86.0],2022-01-28 10:00
...,...,...,...,...,...,...,...,...,...,...
1299,2022-01-28T16:18:26.388,24:0A:C4:4E:E4:2C,da:a9:21:02:6a:d1,0.0,4317.0,139.0,290.0,1.0,-75.0],2022-01-28 16:18
1300,2022-01-28T16:18:27.048,24:0A:C4:4E:E4:2C,f4:34:f0:d3:cc:dd,0.0,132.0,0.0,7.0,1.0,-78.0],2022-01-28 16:18
1301,2022-01-28T16:18:25.668,24:0A:C4:4E:E4:2C,f0:ec:c5:2e:59:9f,0.0,3012.0,99.0,202.0,1.0,-77.0],2022-01-28 16:18
1302,2022-01-28T16:18:26.848,24:0A:C4:4E:E4:2C,fe:2d:9c:89:36:99,0.0,2652.0,90.0,181.0,1.0,-71.0],2022-01-28 16:18
1303,2022-01-28T16:18:26.888,24:0A:C4:4E:E4:2C,e7:ff:ea:af:b2:f6,0.0,751.0,27.0,47.0,1.0,-82.0],2022-01-28 16:18

In [114]:
da060118['Day']=da060118['Time']
for i in range(0,da060118['Time'].count()):
    da060118['Day'][i]=da060118['Time'][i][:10]

In [115]:
da060118['Calorie']=da060118['Calorie'].astype(float)
da060118['Km']=da060118['Km'].astype(float)
da060118['HeartRate']=da060118['HeartRate'].astype(float)
da060118['StepCount']=da060118['StepCount'].astype(float)
da060118['HeartRate']=da060118['HeartRate'].astype(int)
da060118['StepCount']=da060118['StepCount'].astype(int)
da060118['Calorie']=da060118['Calorie'].astype(int)
da060118['Km']=da060118['Km'].astype(int)

In [116]:
def ID_p(id,t): 
    from io import StringIO 
    import datetime 
    io = StringIO() 
    a=da060118[da060118['ID'].str.contains(id)] 
    a=a.reset_index()

# sc와hr의 값이 모두 0일경우 삭제 - 등원하지 않았을때의 경우를 삭제
#    for i in range(0,len(a)-1):
#        if (a['StepCount'][i]==0 & a['HeartRate'][i]==0) & (a['HeartRate'][i+1]==0 & a['StepCount'][i+1]==0):
#            a.drop(index=[i],axis=0,inplace=True)
# 중복데이터 제거
    a.drop_duplicates(['HeartRate','StepCount','Day'],keep='last',inplace=True,ignore_index = True)
    
# 누적걸음수 -> 현재걸음수
# 닐이 같을 경우에만 stepcount의 값을 앞값으로 채움
    for i in range(0,len(a)-1):
        if (a['Day'][i]==a['Day'][i+1])and(a['StepCount'][i]==0 & a['HeartRate'][i] != 0):
            a['StepCount']=a['StepCount'].replace(0, np.NaN)
            a['StepCount']=a['StepCount'].fillna(method='ffill')
            a.reset_index()
            a['StepCount']=a['StepCount'].fillna(0)
            a['StepCount'][1]
            
# 누적걸음수 -> 현재걸음수
    a['sc_']=a['StepCount']
    for i in range(0,len(a)-1):
        if a['Day'][i]==a['Day'][i+1] and a['StepCount'][i]<=a['StepCount'][i+1]:
            a['sc_'][i+1]=int(a['StepCount'][i+1])-int(a['StepCount'][i])

# 누적칼로리 -> 현재칼로리
#    a['Cal']=a['Calorie']
#    for i in range(0,len(a)-1):
#        if a['Day'][i]==a['Day'][i+1] and a['Calorie'][i]<=a['Calorie'][i+1]:
#            a['Cal'][i+1]=int(a['Calorie'][i+1])-int(a['Calorie'][i])            
            
            
            
# 초기화가 안된경우 1. 어제데이터가 연결되어 있는 경우 
# > stepcount[0]의 값이 != 0
# 초기화가 안된경우 2. 0의 값이였다 스마트밴드를 착용함과 동시에 매우 높은 숫자가 찍히는 경우
# > heartrate[1] != 0 and stepcount[1] >= 500 - 이 숫자에 대해선 검토가 필요
    a['Date'] = pd.to_datetime(a['Date'])
    date_=a['Date'].dt.day.unique()
    ind=[]
    for i in range(0,len(date_)):
        a['Date'] = pd.to_datetime(a['Date'])
        step_=a.loc[a['Date'].dt.day==date_[i]]
        step_=step_.reset_index()
        if len(step_)>1:
#초기화가 안된경우 1
            if (step_['StepCount'][0] != 0):
                ind.append(step_['level_0'][0])
    for i in range(0,len(ind)):
        a['sc_'][ind[i]]=0
# 따로 진행 - 둘다 중복의 경우를 생각
#초기화가 안된경우 2
        if len(step_)>1:
            if (step_['StepCount'][1] >= 480):
                ind.append(step_['level_0'][1]) 
    for i in range(0,len(ind)):
        a['sc_'][ind[i]]=0

    
# HeartRate의 값이 0 일경우 다 삭제
    dam=a
    dam['Date'] = pd.to_datetime(dam['Date'])
    dam['HeartRate']=dam['HeartRate'].replace(0,np.NaN)
    dam=dam.dropna()
    dam.reset_index()
    
    
# 날짜별로 원하는 시간대로 분할
    da=[]
    for i in range(0,len(date_)):
        globals()['da_m'+str(i)]=dam.loc[dam['Date'].dt.day==date_[i]]
        globals()['da_m'+str(i)]=globals()['da_m'+str(i)].set_index('Date')
        globals()['da_m'+str(i)]=globals()['da_m'+str(i)].resample(t).mean()
        globals()['da_m'+str(i)]=globals()['da_m'+str(i)].replace(0, np.NaN)
        globals()['da_m'+str(i)]=globals()['da_m'+str(i)].interpolate(method='linear',limit_direction='both')
        globals()['da_m'+str(i)]=globals()['da_m'+str(i)].reset_index()
        da.append(globals()['da_m'+str(i)])
        # 다시 합
        my_m = pd.concat(da)
        
#10~16시 범위내 
    my_m=my_m.set_index('Date')
    my_m=my_m.between_time('10:00','16:00')
    my_m=my_m.reset_index()
    
# 값 삭제 및 채우기
    my_m['ID']=id
    my_m.drop('StepCount',axis=1,inplace=True)
    my_m.drop('index',axis=1,inplace=True)
    #my_m.drop('Rssi',axis=1,inplace=True)
    #my_m.drop('DeviceWear',axis=1,inplace=True)
    #my_m.drop('GatewayID',axis=1,inplace=True)
    my_m=my_m.reset_index(drop=True)
    my_m['Day']=my_m['Date']
    my_m['time']=my_m['Date']
    for i in range(0,len(my_m)):
        my_m['Day'][i]=my_m['Date'][i].date()
        my_m['time'][i]=my_m['Date'][i].time()
    #my_m=my_m.dropna()
    my_m=my_m.reset_index(drop=True)

    
#데이터의 양이 적은 경우 삭제 - (3시간이하의 경우 삭제)
    a=my_m['Date'].dt.day.unique()
    for i in range(0,len(a)):
        aa=my_m.loc[my_m['Date'].dt.day== i]
        if len(aa['Date'].dt.hour.unique()) <= 3:
            my_m.drop(my_m.loc[my_m['Date'].dt.day== i].index,inplace=True)
    my_m=my_m.reset_index(drop=True)
    
# 요일 데이터
    days=['Mon','Tue','Wed','Thu','Fri','Sat','Sun']
    my_m['week']= my_m['Day']
    for i in range(0,len(my_m)):
            my_m['week'][i]=days[my_m['Day'][i].weekday()]
    # 주말 삭제
    my_m.drop(my_m.loc[(my_m['week']=='Sat')|(my_m['week']=='Sun')].index,inplace=True)
    print(my_m[:],error_d,file=io,sep = '\t')
   
    return my_m

In [117]:
def error_d(id):
    from io import StringIO 
    from datetime import datetime, timedelta
    io = StringIO() 
    a=da060118[da060118['ID'].str.contains(id)] 
    a=a.reset_index()
    a.drop_duplicates(['HeartRate','StepCount','Date'],keep='last',inplace=True,ignore_index = True)
    a['Date'] = pd.to_datetime(a['Date'])
    date_=a['Date'].dt.day.unique()
    a['Date'][0]
    error_d=[]
    for i in range(0,len(date_)):
        for j in range(9,15):
            da_=a.loc[a['Date'].dt.day==date_[i]]
            da9= da_.loc[(da_['Date'].dt.hour == j)]
            da9=da9.reset_index()
            da10= da_.loc[(da_['Date'].dt.hour == j+1)]
            da11= da_.loc[(da_['Date'].dt.hour == j+2)]
            da11=da11.reset_index()
            if (len(da9) > 0 and len(da11)>0):
                if (len(da9.loc[(da9['HeartRate'] != 0)]) > 5 and len(da10) == 0 and int(da11['StepCount'][0])-int(da9['StepCount'][-1:]) >= 500):
                    error_d.append(date_[i])
    for i in range(0,len(a)-1):
        if (a['Day'][i]==a['Day'][i+1])and(a['StepCount'][i]==0 & a['HeartRate'][i] != 0):
            a['StepCount']=a['StepCount'].replace(0, np.NaN)
            a['StepCount']=a['StepCount'].fillna(method='ffill')
            a.reset_index()
            a['StepCount']=a['StepCount'].fillna(0)
            a['StepCount'][1]
    # 누적걸음수 -> 현재걸음수
    # 시간으로 한시간 차이일 경우 - 12:00 > 11:59 분의 경우에도 들어가게됨
    a['sc_']=a['StepCount']
    for i in range(0,len(a)-1):
        if a['Day'][i]==a['Day'][i+1] and a['StepCount'][i]<=a['StepCount'][i+1]:
            a['sc_'][i+1]=int(a['StepCount'][i+1])-int(a['StepCount'][i])
        if (a['Date'][i].day==a['Date'][i+1].day):
            if (a['Date'][i+1] - a['Date'][i] > timedelta(hours=1,minutes=-20) and a['StepCount'][i+1] - a['StepCount'][i]>=500):
                error_d.append(a['Date'][i].day)
    error_d=list(set(error_d))
    return error_d

In [118]:
def all_m(time): 
    da=[]
    from io import StringIO
    import datetime
    io = StringIO()
    da06_10=da060118[da060118['Time'].str.endswith('0')]
    idd=da06_10['ID'].unique()
    all_err=[]
    for i in range(0,len(idd)):
        all_err.append(error_d(idd[i]))
    all_err = sum(all_err, [])
    all_err=np.unique(all_err)
    id_=[]
    for i in range(0,len(idd)):
        if len(da06_10.loc[da06_10['ID']==idd[i]]) >= 10:
            id_.append(idd[i])
    for i in range(0,len(id_)):
        globals()['m_da{}'.format(i)] = ID_p(id_[i],time)
        da.append(globals()['m_da{}'.format(i)])
    all=pd.concat(da,ignore_index=True)
    all=all.reset_index()
    #all.drop('GatewayTime',axis=1,inplace=True)
    all.drop('index',axis=1,inplace=True)
    #야외활동의심 데이터
    all['error']= 'indoor'
    for i in range(0,len(all)):
        for j in range(0,len(all_err)):
            if all['Date'][i].day==all_err[j]:
                all['error'][i]='outdoor'
    print(all[:],file=io,sep = '\t')
    return all

In [119]:
all=all_m('10T')

C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:102: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:120: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:102: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:120: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:102: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:120: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:102: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:120: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:102: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:120: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:102: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:120: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:102: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:120: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [120]:
all

,Date,HeartRate,Calorie,Km,sc_,ID,Day,time,week,error
0,2022-01-28 10:00:00,109.600000,92.100000,189.800000,51.900000,ce:75:da:5a:5e:82,2022-01-28,10:00:00,Fri,indoor
1,2022-01-28 10:10:00,111.000000,109.300000,224.100000,32.200000,ce:75:da:5a:5e:82,2022-01-28,10:10:00,Fri,indoor
2,2022-01-28 10:20:00,96.600000,119.300000,245.900000,43.800000,ce:75:da:5a:5e:82,2022-01-28,10:20:00,Fri,indoor
3,2022-01-28 10:30:00,107.875000,130.125000,269.750000,16.875000,ce:75:da:5a:5e:82,2022-01-28,10:30:00,Fri,indoor
4,2022-01-28 10:40:00,95.333333,132.000000,273.666667,14.666667,ce:75:da:5a:5e:82,2022-01-28,10:40:00,Fri,indoor
...,...,...,...,...,...,...,...,...,...,...
162,2022-01-28 14:00:00,80.500000,20.916667,35.791667,13.041667,e7:ff:ea:af:b2:f6,2022-01-28,14:00:00,Fri,indoor
163,2022-01-28 14:10:00,75.500000,27.000000,45.000000,12.000000,e7:ff:ea:af:b2:f6,2022-01-28,14:10:00,Fri,indoor
164,2022-01-28 14:20:00,75.000000,27.000000,45.000000,12.000000,e7:ff:ea:af:b2:f6,2022-01-28,14:20:00,Fri,indoor
165,2022-01-28 14:30:00,74.500000,27.000000,45.000000,12.000000,e7:ff:ea:af:b2:f6,2022-01-28,14:30:00,Fri,indoor
166,2022-01-28 14:40:00,74.000000,27.000000,45.000000,12.000000,e7:ff:ea:af:b2:f6,2022-01-28,14:40:00,Fri,indoor

In [51]:
#all.drop('Rssi',axis=1,inplace=True)
all.drop('DeviceWear',axis=1,inplace=True)
#all.drop('GatewayID',axis=1,inplace=True)
#all.drop('Time',axis=1,inplace=True)

KeyError: "['DeviceWear'] not found in axis"

In [121]:
all

,Date,HeartRate,Calorie,Km,sc_,ID,Day,time,week,error
0,2022-01-28 10:00:00,109.600000,92.100000,189.800000,51.900000,ce:75:da:5a:5e:82,2022-01-28,10:00:00,Fri,indoor
1,2022-01-28 10:10:00,111.000000,109.300000,224.100000,32.200000,ce:75:da:5a:5e:82,2022-01-28,10:10:00,Fri,indoor
2,2022-01-28 10:20:00,96.600000,119.300000,245.900000,43.800000,ce:75:da:5a:5e:82,2022-01-28,10:20:00,Fri,indoor
3,2022-01-28 10:30:00,107.875000,130.125000,269.750000,16.875000,ce:75:da:5a:5e:82,2022-01-28,10:30:00,Fri,indoor
4,2022-01-28 10:40:00,95.333333,132.000000,273.666667,14.666667,ce:75:da:5a:5e:82,2022-01-28,10:40:00,Fri,indoor
...,...,...,...,...,...,...,...,...,...,...
162,2022-01-28 14:00:00,80.500000,20.916667,35.791667,13.041667,e7:ff:ea:af:b2:f6,2022-01-28,14:00:00,Fri,indoor
163,2022-01-28 14:10:00,75.500000,27.000000,45.000000,12.000000,e7:ff:ea:af:b2:f6,2022-01-28,14:10:00,Fri,indoor
164,2022-01-28 14:20:00,75.000000,27.000000,45.000000,12.000000,e7:ff:ea:af:b2:f6,2022-01-28,14:20:00,Fri,indoor
165,2022-01-28 14:30:00,74.500000,27.000000,45.000000,12.000000,e7:ff:ea:af:b2:f6,2022-01-28,14:30:00,Fri,indoor
166,2022-01-28 14:40:00,74.000000,27.000000,45.000000,12.000000,e7:ff:ea:af:b2:f6,2022-01-28,14:40:00,Fri,indoor

In [48]:
all

,Date,HeartRate,Calorie,Km,sc_,ID,Rssi,Day,time,week,error
0,2022-01-26 10:50:00,90.555556,8.777778,20.222222,58.000000,cb:71:72:65:d7:ea,NaN,2022-01-26,10:50:00,Wed,outdoor
1,2022-01-26 11:00:00,97.250000,17.625000,41.375000,18.625000,cb:71:72:65:d7:ea,NaN,2022-01-26,11:00:00,Wed,outdoor
2,2022-01-26 10:00:00,100.666667,14.600000,30.200000,47.333333,ee:0a:15:a0:34:e7,NaN,2022-01-26,10:00:00,Wed,outdoor
3,2022-01-26 10:10:00,104.333333,16.200000,33.400000,47.333333,ee:0a:15:a0:34:e7,NaN,2022-01-26,10:10:00,Wed,outdoor
4,2022-01-26 10:20:00,108.000000,17.800000,36.600000,47.333333,ee:0a:15:a0:34:e7,NaN,2022-01-26,10:20:00,Wed,outdoor
...,...,...,...,...,...,...,...,...,...,...,...
223,2022-01-26 12:10:00,108.777778,182.000000,347.111111,58.000000,e2:fa:c0:9b:15:57,NaN,2022-01-26,12:10:00,Wed,outdoor
224,2022-01-26 12:20:00,100.935185,182.000000,231.740741,44.666667,e2:fa:c0:9b:15:57,NaN,2022-01-26,12:20:00,Wed,outdoor
225,2022-01-26 12:30:00,93.092593,182.000000,116.370370,31.333333,e2:fa:c0:9b:15:57,NaN,2022-01-26,12:30:00,Wed,outdoor
226,2022-01-26 12:40:00,85.250000,182.000000,1.000000,18.000000,e2:fa:c0:9b:15:57,NaN,2022-01-26,12:40:00,Wed,outdoor
227,2022-01-26 12:50:00,118.625000,182.000000,1.000000,18.000000,e2:fa:c0:9b:15:57,NaN,2022-01-26,12:50:00,Wed,outdoor

In [122]:
for i in range(0,len(all)):
    all['ID'][i]=all['ID'][i].replace(':','')

C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [123]:
all['Name']=all['ID']

In [124]:
for i in range(0,len(all)):
    all['Name'][i]=all['Name'][i].replace('e2fac09b1557', '임시우')
    all['Name'][i]=all['Name'][i].replace('cb717265d7ea', '심이준')
    all['Name'][i]=all['Name'][i].replace('caf1eb57aba5', '조아영')
    all['Name'][i]=all['Name'][i].replace('e2418e9e143f', '황아민')
    all['Name'][i]=all['Name'][i].replace('d8297dfa6a9f', '김태민')
    all['Name'][i]=all['Name'][i].replace('d4c0fc21e3f0', '김서율')
    all['Name'][i]=all['Name'][i].replace('f0656772a71f', '이하민')
    all['Name'][i]=all['Name'][i].replace('d9b2c13efdc4', '정하은')
    all['Name'][i]=all['Name'][i].replace('ee0a15a034e7', '최수아')
    all['Name'][i]=all['Name'][i].replace('cb4d4a2d95d7', '권민찬')
    all['Name'][i]=all['Name'][i].replace('f0ecc52e599f', '이하율')
    all['Name'][i]=all['Name'][i].replace('c396da72a0f1', '이은호')
    all['Name'][i]=all['Name'][i].replace('daa921026ad1', '강하늘')
    all['Name'][i]=all['Name'][i].replace('fe2d9c893699', '나지호')
    all['Name'][i]=all['Name'][i].replace('e7ffeaafb2f6', '정하율')
    all['Name'][i]=all['Name'][i].replace('f434f0d3ccdd', '김민욱')
    all['Name'][i]=all['Name'][i].replace('e6950b5db6d4', '장하준')
    all['Name'][i]=all['Name'][i].replace('fb0ed04863fb', '이윤후')
    all['Name'][i]=all['Name'][i].replace('e771ff735afc', '김루시아')
    all['Name'][i]=all['Name'][i].replace('f7215097c91d', '심보겸')
    all['Name'][i]=all['Name'][i].replace('cf36a37b02dc', '조용준')
    all['Name'][i]=all['Name'][i].replace('f247560b661c', '최유영')
    all['Name'][i]=all['Name'][i].replace('c4072b2ed286', '김서연')
    all['Name'][i]=all['Name'][i].replace('e928c8ab559b', '박한')
    all['Name'][i]=all['Name'][i].replace('dc3f98683e86', '김강현')
    all['Name'][i]=all['Name'][i].replace('eab6956ce438', '김도겸')
    all['Name'][i]=all['Name'][i].replace('cd16d0eb872b', '윤승주')
    all['Name'][i]=all['Name'][i].replace('f884fa53691b', '황아준')
    all['Name'][i]=all['Name'][i].replace('c87637901ff2', '김태희')
    all['Name'][i]=all['Name'][i].replace('c31ead1fb559', '이로아')
    all['Name'][i]=all['Name'][i].replace('e380bee19432', '정하준')
    all['Name'][i]=all['Name'][i].replace('cbc481754494', '홍다연')
    all['Name'][i]=all['Name'][i].replace('d7d9d92029e8', '최서윤')
    all['Name'][i]=all['Name'][i].replace('ce4555dab851', '하린')
    all['Name'][i]=all['Name'][i].replace('cc1c82823f60', '임지호')
    all['Name'][i]=all['Name'][i].replace('fa4d2b518470','원창호')
    all['Name'][i]=all['Name'][i].replace('f3d821b36964', '류희원')
    all['Name'][i]=all['Name'][i].replace('e72478d5d379', '변설하')
    all['Name'][i]=all['Name'][i].replace('c2822fc55e74', '송금별')
    all['Name'][i]=all['Name'][i].replace('dcbf93d2bc77', '왕채빈')
    all['Name'][i]=all['Name'][i].replace('eb2cb6eb4188', '이원선')
    all['Name'][i]=all['Name'][i].replace('ce75da5a5e82', '김태준')
    all['Name'][i]=all['Name'][i].replace('cc572a63c312', '고다현')
    all['Name'][i]=all['Name'][i].replace('ff4790c7d3b3', '김태림')
    all['Name'][i]=all['Name'][i].replace('c63745261206', '이예원')
    all['Name'][i]=all['Name'][i].replace('f5f6e24ba9a1', '이예나')
    all['Name'][i]=all['Name'][i].replace('f4fee38bff3a', '이하진')
    all['Name'][i]=all['Name'][i].replace('e3294717ed61', '박주안')
    all['Name'][i]=all['Name'][i].replace('fba1102cbc13', '이서윤')
    all['Name'][i]=all['Name'][i].replace('cbaeb3f4f03a', '정수호')
    all['Name'][i]=all['Name'][i].replace('ef6b075c6559', '박준')
    all['Name'][i]=all['Name'][i].replace('f6ab31a4b2f6', '최아윤')
    all['Name'][i]=all['Name'][i].replace('c354ef202296', '최온유')
    all['Name'][i]=all['Name'][i].replace('c714d8a85267', '김선우')

C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:52: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\AICTTechPlan04\anaconda3\lib\site-packages\ipykernel_launcher.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [125]:
all

,Date,HeartRate,Calorie,Km,sc_,ID,Day,time,week,error,Name
0,2022-01-28 10:00:00,109.600000,92.100000,189.800000,51.900000,ce75da5a5e82,2022-01-28,10:00:00,Fri,indoor,김태준
1,2022-01-28 10:10:00,111.000000,109.300000,224.100000,32.200000,ce75da5a5e82,2022-01-28,10:10:00,Fri,indoor,김태준
2,2022-01-28 10:20:00,96.600000,119.300000,245.900000,43.800000,ce75da5a5e82,2022-01-28,10:20:00,Fri,indoor,김태준
3,2022-01-28 10:30:00,107.875000,130.125000,269.750000,16.875000,ce75da5a5e82,2022-01-28,10:30:00,Fri,indoor,김태준
4,2022-01-28 10:40:00,95.333333,132.000000,273.666667,14.666667,ce75da5a5e82,2022-01-28,10:40:00,Fri,indoor,김태준
...,...,...,...,...,...,...,...,...,...,...,...
162,2022-01-28 14:00:00,80.500000,20.916667,35.791667,13.041667,e7ffeaafb2f6,2022-01-28,14:00:00,Fri,indoor,정하율
163,2022-01-28 14:10:00,75.500000,27.000000,45.000000,12.000000,e7ffeaafb2f6,2022-01-28,14:10:00,Fri,indoor,정하율
164,2022-01-28 14:20:00,75.000000,27.000000,45.000000,12.000000,e7ffeaafb2f6,2022-01-28,14:20:00,Fri,indoor,정하율
165,2022-01-28 14:30:00,74.500000,27.000000,45.000000,12.000000,e7ffeaafb2f6,2022-01-28,14:30:00,Fri,indoor,정하율
166,2022-01-28 14:40:00,74.000000,27.000000,45.000000,12.000000,e7ffeaafb2f6,2022-01-28,14:40:00,Fri,indoor,정하율

In [126]:
all['Name'].unique()

array(['김태준', '나지호', '강하늘', '장하준', '김민욱', '이하율', '정하율'], dtype=object)

In [127]:
all.to_csv('D:/DB/2200128.csv', index=False, encoding='cp949')

In [34]:
36+18

54